# 6. Faça um programa que encontre todas as chaves que estão associadas a um 
# determinado valor em um dicionário. O programa deve preencher um dicionário pelo 
# usuário e, a partir desse dicionário e de um valor indicado pelo usuário, encontrar e 
# exibir as chaves relacionadas ao valor em forma de lista. 

champions = {
    "Aatrox": "Lutador",
    "Ahri": "Mago",
    "Akali": "Assassino",
    "Alistar": "Suporte",
    "Amumu": "Tanque",
    "Anivia": "Mago",
    "Annie": "Mago",
    "Aphelios": "Atirador",
    "Ashe": "Atirador",
    "Aurelion Sol": "Mago",
    "Azir": "Mago",
    "Bard": "Suporte",
    "Blitzcrank": "Suporte",
    "Brand": "Mago",
    "Braum": "Suporte",
    "Caitlyn": "Atirador",
    "Camille": "Lutador",
    "Cassiopeia": "Mago",
    "Cho'Gath": "Tanque",
    "Corki": "Atirador",
    "Darius": "Lutador",
    "Diana": "Lutador",
    "Dr. Mundo": "Tanque",
    "Draven": "Atirador",
    "Ekko": "Assassino",
    "Elise": "Assassino",
    "Evelynn": "Assassino",
    "Ezreal": "Atirador",
    "Fiddlesticks": "Mago",
    "Fiora": "Lutador",
    "Fizz": "Assassino",
    "Galio": "Tanque",
    "Gangplank": "Lutador",
    "Garen": "Lutador",
    "Gnar": "Lutador",
    "Gragas": "Tanque",
    "Graves": "Atirador",
    "Hecarim": "Lutador",
    "Heimerdinger": "Mago",
    "Illaoi": "Lutador",
    "Irelia": "Lutador",
    "Ivern": "Suporte",
    "Janna": "Suporte",
    "Jarvan IV": "Lutador",
    "Jax": "Lutador",
    "Jayce": "Lutador",
    "Jhin": "Atirador",
    "Jinx": "Atirador",
    "Kai'Sa": "Atirador",
    "Kalista": "Atirador",
    "Karma": "Suporte",
    "Karthus": "Mago",
    "Kassadin": "Assassino",
    "Katarina": "Assassino",
    "Kayle": "Lutador",
    "Kayn": "Lutador",
    "Kennen": "Mago",
    "Kha'Zix": "Assassino",
    "Kindred": "Atirador",
    "Kled": "Lutador",
    "Kog'Maw": "Atirador",
    "LeBlanc": "Assassino",
    "Lee Sin": "Lutador",
    "Leona": "Tanque",
    "Lillia": "Lutador",
    "Lissandra": "Mago",
    "Lucian": "Atirador",
    "Lulu": "Suporte",
    "Lux": "Mago",
    "Malphite": "Tanque",
    "Malzahar": "Mago",
    "Maokai": "Tanque",
    "Master Yi": "Lutador",
    "Miss Fortune": "Atirador",
    "Mordekaiser": "Lutador",
    "Morgana": "Mago",
    "Nami": "Suporte",
    "Nasus": "Lutador",
    "Nautilus": "Tanque",
    "Neeko": "Mago",
    "Nidalee": "Assassino",
    "Nocturne": "Assassino",
    "Nunu & Willump": "Tanque",
    "Olaf": "Lutador",
    "Orianna": "Mago",
    "Ornn": "Tanque",
    "Pantheon": "Lutador",
    "Poppy": "Tanque",
    "Pyke": "Suporte",
    "Qiyana": "Assassino",
    "Quinn": "Atirador",
    "Rakan": "Suporte",
    "Rammus": "Tanque",
    "Rek'Sai": "Lutador",
    "Rell": "Tanque",
    "Renekton": "Lutador",
    "Rengar": "Assassino",
    "Riven": "Lutador",
    "Rumble": "Lutador",
    "Ryze": "Mago",
    "Samira": "Atirador",
    "Sejuani": "Tanque",
    "Senna": "Atirador",
    "Seraphine": "Suporte",
    "Sett": "Lutador",
    "Shaco": "Assassino",
    "Shen": "Tanque",
    "Shyvana": "Lutador",
    "Singed": "Tanque",
    "Sion": "Tanque",
    "Sivir": "Atirador",
    "Skarner": "Lutador",
    "Sona": "Suporte",
    "Soraka": "Suporte",
    "Swain": "Mago",
    "Sylas": "Lutador",
    "Syndra": "Mago",
    "Tahm Kench": "Suporte",
    "Taliyah": "Mago",
    "Talon": "Assassino",
    "Taric": "Suporte",
    "Teemo": "Mago",
    "Thresh": "Suporte",
    "Tristana": "Atirador",
    "Trundle": "Lutador",
    "Tryndamere": "Lutador",
    "Twisted Fate": "Mago",
    "Twitch": "Atirador",
    "Udyr": "Lutador",
    "Urgot": "Lutador",
    "Varus": "Atirador",
    "Vayne": "Atirador",
    "Veigar": "Mago",
    "Vel'Koz": "Mago",
    "Vi": "Lutador",
    "Viego": "Lutador",
    "Viktor": "Mago",
    "Vladimir": "Mago",
    "Volibear": "Lutador",
    "Warwick": "Lutador",
    "Wukong": "Lutador",
    "Xayah": "Atirador",
    "Xerath": "Mago",
    "Xin Zhao": "Lutador",
    "Yasuo": "Lutador",
    "Yone": "Lutador",
    "Yorick": "Lutador",
    "Yuumi": "Suporte",
    "Zac": "Tanque",
    "Zed": "Assassino",
    "Ziggs": "Mago",
    "Zilean": "Suporte",
    "Zoe": "Mago",
    "Zyra": "Suporte"
}

print("Digite uma função dentre as seguintes opções para ver quais campeões do League of Legends fazem essa função: ")
print("| Assassino | Lutador | Mago | Atirador | Suporte | Tanque |\n")

while True:

    function = str(input("Função: ")).lower()

    if function in ["assassino", "lutador", "mago", "atirador", "suporte", "tanque"]:
        break
    else:
        print("Essa função não existe, verifique a ortografia.")

finalArray = []

for champion in champions:
    if champions[champion] == function:
        finalArray.append(champion)
        print(champion)

print(finalArray)
print("Atenção esse código ta com erros")
# verificar se função existe, colocar todos da função numa lista, exibir todos